apiVersion: v1
kind: Namespace
metadata:
  name: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-server
  namespace: jaeger
  labels:
    app: jaeger-server
spec:
  selector:
    app: jaeger-server
  ports:
    - name: jaever-view
      protocol: TCP
      port: 16686
      targetPort: 16686
      nodePort: 31686
    - protocol: TCP
      name: jaever-data
      port: 14250
      targetPort: 14250
      nodePort: 31650
    - protocol: TCP
      name: jaever-data2
      port: 16685
      targetPort: 16685
      nodePort: 31685
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-server
  namespace: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger-server
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger-server
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.29
        ports:
          - containerPort:  16686
            protocol: TCP
          - containerPort:  16685
            protocol: TCP
          - containerPort:  14250
            protocol: TCP
