apiVersion: v1
kind: Namespace
metadata:
  name: zipkin
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-server
  namespace: zipkin
  labels:
    app: zipkin-server
spec:
  selector:
    app: zipkin-server
  ports:
    - name: zipkin-view
      protocol: TCP
      port: 9411
      targetPort: 9411
      nodePort: 30411
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-server
  namespace: zipkin
spec:
  selector:
    matchLabels:
      app: zipkin-server
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin-server
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:latest
        ports:
          - containerPort: 9411
            protocol: TCP

